// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cholRcpp
void cholRcpp(arma::mat& R, const arma::mat& M, const bool& lower);
RcppExport SEXP _fastchol_cholRcpp(SEXP RSEXP, SEXP MSEXP, SEXP lowerSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const bool& >::type lower(lowerSEXP);
    cholRcpp(R, M, lower);
    return R_NilValue;
END_RCPP
}
// LtoU_Rcpp
void LtoU_Rcpp(arma::mat& U, const arma::mat& L);
RcppExport SEXP _fastchol_LtoU_Rcpp(SEXP USEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    LtoU_Rcpp(U, L);
    return R_NilValue;
END_RCPP
}
// UtoL_Rcpp
void UtoL_Rcpp(arma::mat& L, const arma::mat& U);
RcppExport SEXP _fastchol_UtoL_Rcpp(SEXP LSEXP, SEXP USEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    UtoL_Rcpp(L, U);
    return R_NilValue;
END_RCPP
}
// cholupL_Rcpp
void cholupL_Rcpp(arma::mat& L, arma::vec& x);
RcppExport SEXP _fastchol_cholupL_Rcpp(SEXP LSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type x(xSEXP);
    cholupL_Rcpp(L, x);
    return R_NilValue;
END_RCPP
}
// cholupU_Rcpp
void cholupU_Rcpp(arma::mat& U, arma::vec& x);
RcppExport SEXP _fastchol_cholupU_Rcpp(SEXP USEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type x(xSEXP);
    cholupU_Rcpp(U, x);
    return R_NilValue;
END_RCPP
}
// choldownL_Rcpp
void choldownL_Rcpp(arma::mat& L, arma::vec& x);
RcppExport SEXP _fastchol_choldownL_Rcpp(SEXP LSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type x(xSEXP);
    choldownL_Rcpp(L, x);
    return R_NilValue;
END_RCPP
}
// choldownU_Rcpp
void choldownU_Rcpp(arma::mat& U, arma::vec& x);
RcppExport SEXP _fastchol_choldownU_Rcpp(SEXP USEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type x(xSEXP);
    choldownU_Rcpp(U, x);
    return R_NilValue;
END_RCPP
}
// choldropL_Rcpp
void choldropL_Rcpp(arma::mat& L0, const arma::mat& L, const int& k);
RcppExport SEXP _fastchol_choldropL_Rcpp(SEXP L0SEXP, SEXP LSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type L0(L0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int& >::type k(kSEXP);
    choldropL_Rcpp(L0, L, k);
    return R_NilValue;
END_RCPP
}
// choldropU_Rcpp
void choldropU_Rcpp(arma::mat& U0, const arma::mat& U, const int& k);
RcppExport SEXP _fastchol_choldropU_Rcpp(SEXP U0SEXP, SEXP USEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type U0(U0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< const int& >::type k(kSEXP);
    choldropU_Rcpp(U0, U, k);
    return R_NilValue;
END_RCPP
}
// choladdL_Rcpp
void choladdL_Rcpp(arma::mat& Lout, const arma::mat& Lin, const arma::vec& z, const int& k);
RcppExport SEXP _fastchol_choladdL_Rcpp(SEXP LoutSEXP, SEXP LinSEXP, SEXP zSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Lout(LoutSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Lin(LinSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const int& >::type k(kSEXP);
    choladdL_Rcpp(Lout, Lin, z, k);
    return R_NilValue;
END_RCPP
}
// Lsolve_Rcpp
void Lsolve_Rcpp(const arma::mat& L, arma::vec& x);
RcppExport SEXP _fastchol_Lsolve_Rcpp(SEXP LSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type x(xSEXP);
    Lsolve_Rcpp(L, x);
    return R_NilValue;
END_RCPP
}
// Usolve_Rcpp
void Usolve_Rcpp(const arma::mat& U, arma::vec& x);
RcppExport SEXP _fastchol_Usolve_Rcpp(SEXP USEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type U(USEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type x(xSEXP);
    Usolve_Rcpp(U, x);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastchol_cholRcpp", (DL_FUNC) &_fastchol_cholRcpp, 3},
    {"_fastchol_LtoU_Rcpp", (DL_FUNC) &_fastchol_LtoU_Rcpp, 2},
    {"_fastchol_UtoL_Rcpp", (DL_FUNC) &_fastchol_UtoL_Rcpp, 2},
    {"_fastchol_cholupL_Rcpp", (DL_FUNC) &_fastchol_cholupL_Rcpp, 2},
    {"_fastchol_cholupU_Rcpp", (DL_FUNC) &_fastchol_cholupU_Rcpp, 2},
    {"_fastchol_choldownL_Rcpp", (DL_FUNC) &_fastchol_choldownL_Rcpp, 2},
    {"_fastchol_choldownU_Rcpp", (DL_FUNC) &_fastchol_choldownU_Rcpp, 2},
    {"_fastchol_choldropL_Rcpp", (DL_FUNC) &_fastchol_choldropL_Rcpp, 3},
    {"_fastchol_choldropU_Rcpp", (DL_FUNC) &_fastchol_choldropU_Rcpp, 3},
    {"_fastchol_choladdL_Rcpp", (DL_FUNC) &_fastchol_choladdL_Rcpp, 4},
    {"_fastchol_Lsolve_Rcpp", (DL_FUNC) &_fastchol_Lsolve_Rcpp, 2},
    {"_fastchol_Usolve_Rcpp", (DL_FUNC) &_fastchol_Usolve_Rcpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastchol(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
