# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cholupL_Rcpp <- function(L, x) {
    invisible(.Call(`_fastchol_cholupL_Rcpp`, L, x))
}

cholupU_Rcpp <- function(U, x) {
    invisible(.Call(`_fastchol_cholupU_Rcpp`, U, x))
}

choldownL_Rcpp <- function(L, x) {
    invisible(.Call(`_fastchol_choldownL_Rcpp`, L, x))
}

choldownU_Rcpp <- function(U, x) {
    invisible(.Call(`_fastchol_choldownU_Rcpp`, U, x))
}

