# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cholRcpp_Rcpp <- function(R, M, lower = TRUE) {
    invisible(.Call(`_fastchol_cholRcpp_Rcpp`, R, M, lower))
}

LtoU_Rcpp <- function(U, L) {
    invisible(.Call(`_fastchol_LtoU_Rcpp`, U, L))
}

UtoL_Rcpp <- function(L, U) {
    invisible(.Call(`_fastchol_UtoL_Rcpp`, L, U))
}

cholupL_Rcpp <- function(L, x) {
    invisible(.Call(`_fastchol_cholupL_Rcpp`, L, x))
}

cholupU_Rcpp <- function(U, x) {
    invisible(.Call(`_fastchol_cholupU_Rcpp`, U, x))
}

choldownL_Rcpp <- function(L, x) {
    invisible(.Call(`_fastchol_choldownL_Rcpp`, L, x))
}

choldownU_Rcpp <- function(U, x) {
    invisible(.Call(`_fastchol_choldownU_Rcpp`, U, x))
}

choldropL_Rcpp <- function(L0, L, k) {
    invisible(.Call(`_fastchol_choldropL_Rcpp`, L0, L, k))
}

choldropU_Rcpp <- function(U0, U, k) {
    invisible(.Call(`_fastchol_choldropU_Rcpp`, U0, U, k))
}

choladdL_Rcpp <- function(Lout, Lin, z, k) {
    invisible(.Call(`_fastchol_choladdL_Rcpp`, Lout, Lin, z, k))
}

Lsolve_Rcpp <- function(L, x) {
    invisible(.Call(`_fastchol_Lsolve_Rcpp`, L, x))
}

Usolve_Rcpp <- function(U, x) {
    invisible(.Call(`_fastchol_Usolve_Rcpp`, U, x))
}

